worker_processes auto;

events {
    worker_connections 1024;
}

http {

    # FRONTEND
    upstream frontend_app {
        server frontend:5173;
    }

    # ORDER LOAD BALANCER
    upstream order_backend {
        least_conn;
        server order-service-1:3001;
        server order-service-2:3005;
    }

    server {

        listen 80;
        server_name localhost;

        # CORS
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS";
        add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization";

        if ($request_method = OPTIONS) {
            return 204;
        }

        # FRONTEND
        location / {
            proxy_pass http://frontend_app;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # USER
        location /user/ {
            proxy_pass http://user:3000/;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # MENU
        location /menu {
            proxy_pass http://menu:3002/menu;
        }

        # PAYMENT
        location /payment {
            proxy_pass http://payment:3003/payment;
        }

        # ORDER
        location /order {
            proxy_pass http://order_backend/order;
        }

        # MONITORING
        location /log {
            proxy_pass http://monitoring:3004/log;
        }

        location /stats {
            proxy_pass http://monitoring:3004/stats;
        }

        location /db-status {
            proxy_pass http://monitoring:3004/db-status;
        }

        location /health {
            proxy_pass http://monitoring:3004/health;
        }
    }
}